apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-resources
  namespace: argocd
  annotations:
    # ESO ve Vault hazır olduktan sonra (Wave 0) çalışmalı
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: platform
  source:
    repoURL: https://github.com/architechturelaboratory/cluster-bootstrap.git
    targetRevision: HEAD
    path: addons/external-secrets/resources
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
