# Tüm namespace'lere default-deny ingress uygula
# TODO Her uygulama kendi NetworkPolicy ile izin açar
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: monitoring
spec:
  podSelector: {}
  policyTypes:
    - Ingress

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: ingress-nginx
spec:
  podSelector: {}
  policyTypes:
    - Ingress

# ingress-nginx'in tüm namespace'lere ulaşmasına izin ver
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-nginx
  namespace: monitoring
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx

---
# Prometheus'un tüm namespace'lerdeki pod'ları scrape etmesine izin ver
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-prometheus-scrape
  namespace: monitoring
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: prometheus
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - port: 8080
          protocol: TCP
        - port: 9090
          protocol: TCP
        - port: 9091
          protocol: TCP
