apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-issuer
  namespace: argocd
  annotations:
    # cert-manager (wave 0) kurulduktan sonra çalışsın
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: platform
  source:
    repoURL: https://github.com/architechturelaboratory/cluster-bootstrap.git
    targetRevision: HEAD
    path: addons/cert-manager/issuer
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
