replicaCount: 1

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

webhook:
  replicaCount: 1

certController:
  replicaCount: 1

# Prometheus metrikleri
serviceMonitor:
  enabled: true
  namespace: monitoring
