apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
  # Bu silinirse tüm alt app'lar da silinir — dikkatli ol
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/architechturelaboratory/cluster-bootstrap.git  # <-- bu repodan okuyacaksın
    targetRevision: HEAD
    path: addons
    directory:
      recurse: true
      include: "*/Application.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
