controller:
  replicaCount: 1

  config:
    use-forwarded-headers: "true"
    ssl-redirect: "true"

  metrics:
    enabled: true

  ingressClassResource:
    name: nginx
    enabled: true
    default: true

  # k3d ile NodePort kullan
  # k3d cluster --port "80:30080@loadbalancer" --port "443:30443@loadbalancer" ile eşleşir
  service:
    type: ClusterIP

  # Dev için tek node'da çalışacak şekilde
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi

defaultBackend:
  enabled: false
